name:                ripfd
version:             0.1.0.0
github:              "davidscholberg/ripfd"
license:             BSD-3-Clause
author:              "David Scholberg"
maintainer:          "recombinant.vector@gmail.com"
copyright:           "2025 David Scholberg"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/davidscholberg/ripfd#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  include-dirs: c
  dependencies:
  - async
  - bytestring
  - directory
  - directory-ospath-streaming
  - filepath
  - pqueue
  - queues
  - regex-tdfa
  - stm

executables:
  ripfd-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - directory
    - ripfd

tests:
  ripfd-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ripfd
